[[repos]]
repo = "local"
hooks = [
  {
    id = "cargo-fmt",
    name = "cargo fmt",
    language = "system",
    entry = "cargo fmt",
    args = ["--check", "--"],
    types = ["rust"],
    pass_filenames = true,
  },
  {
    id = "cargo-clippy",
    name = "cargo clippy",
    language = "system",
    entry = "cargo clippy",
    args = ["--all-targets", "--", "-D", "warnings"],
    types = ["rust"],
    pass_filenames = false,
  },
]
